# Generated by Django 5.1.3 on 2024-12-30 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_rdv_id_patient_alter_rdv_id_secretaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='id_patient',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, related_name='rdv_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='id_secretaire',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='rdv_sec', to=settings.AUTH_USER_MODEL),
        ),
    ]
