# Generated by Django 5.1.3 on 2024-12-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_consultation_id_medecin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='antecedant',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date_consultation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='traitement',
            field=models.TextField(max_length=254),
        ),
    ]
