# Generated by Django 5.1.3 on 2024-12-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_consultation_antecedant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichepatient',
            name='CNAM',
        ),
        migrations.RemoveField(
            model_name='fichepatient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='fichepatient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fichepatient',
            name='id_secretaire',
        ),
        migrations.RemoveField(
            model_name='fichepatient',
            name='profession',
        ),
    ]
