# Generated by Django 5.1.3 on 2024-12-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_fichepatient_cnam_remove_fichepatient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='id_patient',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='id_secretaire',
        ),
        migrations.AddField(
            model_name='rdv',
            name='Nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rdv',
            name='Prénom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
