# Generated by Django 5.1.3 on 2024-12-31 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_rdv_id_patient_remove_rdv_id_secretaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='Nom',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='Prénom',
        ),
        migrations.AddField(
            model_name='rdv',
            name='id_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rdv_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
