# Generated by Django 5.1.3 on 2024-12-31 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_rdv_nom_remove_rdv_prénom_rdv_id_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='id_secretaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rdv_sec', to=settings.AUTH_USER_MODEL),
        ),
    ]
