# Generated by Django 5.1.3 on 2024-12-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_rdv_id_fiche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='id_fiche',
        ),
    ]
