# Generated by Django 5.1.3 on 2024-12-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_rdv_id_fiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='id_fiche',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='id_patient',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
