# Generated by Django 5.1.3 on 2024-12-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_rdv_id_fiche_alter_rdv_id_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='id_patient',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
