# Generated by Django 5.1.3 on 2024-12-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_rdv_id_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='id_fiche',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='id_patient',
        ),
        migrations.AddField(
            model_name='rdv',
            name='id_fiche_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rdv',
            name='id_patient_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
