# Generated by Django 5.1.3 on 2024-12-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_rdv_id_fiche_remove_rdv_id_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdv',
            old_name='id_fiche_nom',
            new_name='id_fiche',
        ),
        migrations.RenameField(
            model_name='rdv',
            old_name='id_patient_nom',
            new_name='id_patient',
        ),
    ]
