# Generated by Django 5.1.3 on 2024-12-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_rename_id_fiche_rdv_fiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichepatient',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
