# Generated by Django 5.1.3 on 2025-01-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_consultation_fiche_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='id_facture',
            new_name='facture',
        ),
    ]
