# Generated by Django 5.1.3 on 2025-01-01 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_rename_id_facture_consultation_facture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='contenue',
            new_name='Observation',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='traitement',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='observation',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='id_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ordonnance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='Traitement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cons_ord', to='pages.ordonnance'),
        ),
    ]
