# Generated by Django 5.1.3 on 2025-01-01 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_ordonnance_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='image',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='url_ordonnance',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='id_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ordonnances', to=settings.AUTH_USER_MODEL),
        ),
    ]
