# Generated by Django 5.1.3 on 2025-01-01 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_remove_ordonnance_image_ordonnance_url_ordonnance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='url_ordonnance',
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='id_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ordonnance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='certificat',
            fields=[
                ('id_ordonnance', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('medicament', models.CharField(max_length=254)),
                ('id_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
