# Generated by Django 5.1.3 on 2025-01-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_remove_ordonnance_url_ordonnance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificat',
            old_name='medicament',
            new_name='contenu',
        ),
        migrations.RenameField(
            model_name='certificat',
            old_name='id_ordonnance',
            new_name='id_certificat',
        ),
    ]
