# Generated by Django 5.1.3 on 2025-01-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_alter_certificat_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificat',
            name='id_patient',
        ),
    ]
