# Generated by Django 5.1.3 on 2025-01-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_certificat_id_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificat',
            name='contenu',
            field=models.TextField(max_length=1000),
        ),
    ]
