# Generated by Django 5.1.3 on 2025-01-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_alter_certificat_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificat',
            name='contenu',
            field=models.TextField(),
        ),
    ]
