# Generated by Django 5.1.3 on 2025-01-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_alter_certificat_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='medicament',
            field=models.TextField(max_length=254),
        ),
    ]
