# Generated by Django 5.1.3 on 2025-01-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_alter_ordonnance_medicament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='medicament',
            field=models.TextField(),
        ),
    ]
