# Generated by Django 5.1.3 on 2025-01-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_alter_ordonnance_medicament'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rdv',
            name='prénom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
