# Generated by Django 5.1.3 on 2025-01-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_rename_nom_rdv_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='last_name',
        ),
    ]
